'use client';
import {useState,type FormEvent,type ReactNode} from 'react';
import Link from 'next/link';
import {LayoutDashboard,FileText,Users,GitBranch,MessageSquare,BriefcaseBusiness,CalendarDays,UserRound,BarChart3,Settings,Heart,Star,Search,Plus,ArrowUpRight,Check,LogOut} from 'lucide-react';
import {Logo} from '@/components/prospekto/logo';
import {LogoutButton} from '@/components/panel/logout-button';
import {Field,PanelButton,Empty} from '@/components/panel/ui';
import {AccountSwitcher} from '@/components/accounts/account-switcher';
import {canManage,destination,stageLabels,typeLabels,type AccountContext,type OnboardingData,type Service,type Stage} from '@/lib/accounts/model';
import {CZECH_REGIONS,normalizeSearch,regionLabel} from '@/lib/company-types';
import type {MarketplaceState,MarketRequest,Lead} from '@/lib/marketplace/model';

const providerNav=[['prehled','Přehled',LayoutDashboard],['poptavky','Poptávky',FileText],['leady','Moje leady',Users],['crm','CRM',GitBranch],['zpravy','Zprávy',MessageSquare],['zakazky','Zakázky',BriefcaseBusiness],['kalendar','Kalendář',CalendarDays],['profil','Profil',UserRound],['statistiky','Statistiky',BarChart3],['nastaveni','Nastavení',Settings]] as const;
const customerNav=[['prehled','Přehled',LayoutDashboard],['poptavky','Moje poptávky',FileText],['nabidky','Nabídky od firem',BriefcaseBusiness],['zpravy','Zprávy',MessageSquare],['dodavatele','Hledat dodavatele',Search],['oblibeni','Oblíbení dodavatelé',Heart],['recenze','Moje recenze',Star],['nastaveni','Nastavení účtu',Settings]] as const;
const czk=(value:number)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(value);
const date=(value:string)=>new Date(value).toLocaleDateString('cs-CZ');
const requestStatus:Record<string,string>={OPEN:'Otevřená',ASSIGNED:'Dodavatel vybraný',CLOSED:'Dokončená'};
const offerStatus:Record<string,string>={SENT:'Odeslaná',ACCEPTED:'Přijatá',REJECTED:'Nepřijatá'};
export function Dashboard({context,initial,view,name,services,profile,team}:{context:AccountContext;initial:MarketplaceState;view:string;name:string;services:Service[];profile:OnboardingData|null;team:{name:string;email:string;role:string}[]}) {
  const account=context.account!,customer=account.type==='CUSTOMER',base=destination(context);
  const nav=customer?customerNav:providerNav;
  const href=(section:string)=>base+(section==='prehled'?'':section+'/');
  const [state,setState]=useState(initial),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[region,setRegion]=useState('');
  const [thread,setThread]=useState('');
  async function act(body:unknown):Promise<boolean> {
    if(busy)return false;setBusy(true);setError('');setNotice('');
    try {
      const response=await fetch('/api/marketplace/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
      const result=await response.json();if(!response.ok)throw new Error(result.error||'Změnu se nepodařilo uložit.');
      setState(result.state);setNotice('Hotovo, změny jsou uložené.');return true;
    }catch(error){setError(error instanceof Error?error.message:'Zkuste to znovu.');return false;}finally{setBusy(false);}
  }
  async function submit(event:FormEvent<HTMLFormElement>,build:(values:Record<string,string>)=>unknown) {
    event.preventDefault();const form=event.currentTarget;
    const values=Object.fromEntries(new FormData(form)) as Record<string,string>;
    if(await act(build(values)))form.reset();
  }
  const EmptyState=({title,children,action}:{title:string;children:ReactNode;action?:ReactNode})=><Empty title={title} action={action}>{children}</Empty>;
  function requestCards(items:MarketRequest[]) {
    return items.length?<div className="m-card-grid">{items.map(r=><article className="p-card m-request-card" key={r.id}><div className="m-card-meta"><span className="p-badge">{services.find(s=>s.id===r.serviceId)?.name}</span><small>{date(r.createdAt)}</small></div><h3>{r.title}</h3><p className="m-clamp">{r.description}</p><p>{r.city} · {regionLabel(r.region)}</p><div className="m-card-meta"><strong>{r.budgetCzk===null?'Rozpočet dohodou':czk(r.budgetCzk)}</strong><span className="p-badge">{requestStatus[r.status]}</span></div>{customer?<div className="m-form-actions"><Link className="p-button p-secondary" href={href('nabidky')}>Zobrazit nabídky</Link>{r.status!=='CLOSED'&&<button className="m-text-button" disabled={busy} onClick={()=>void act({action:'close-request',id:r.id})}>Označit dokončené</button>}</div>:<button className="p-button p-secondary" disabled={busy||state.leads.some(l=>l.requestId===r.id)} onClick={()=>void act({action:'interest',requestId:r.id})}>{state.leads.some(l=>l.requestId===r.id)?'Už je mezi vašimi leady':'Mám zájem o poptávku'}<ArrowUpRight size={16}/></button>}</article>)}</div>:<EmptyState title={customer?'Vaše první poptávka začíná tady.':'Zatím tu nejsou odpovídající poptávky.'} action={customer?<Link className="p-button" href={href('nova-poptavka')}>Vytvořit poptávku</Link>:<Link className="p-button p-secondary" href="/onboarding/?edit=1&step=3">Upravit služby a oblast</Link>}>{customer?'Popište, s čím potřebujete pomoci. Dodavatelé vám mohou poslat nabídku.':'Nové poptávky se zobrazí podle vašich služeb, měst a vybraných krajů.'}</EmptyState>;
  }
  function leadCards(items:Lead[]) {
    return items.length?<div className="m-records">{items.map(l=><article className="p-card m-lead" key={l.id}><div><h3>{l.title}</h3><p>{l.contactName||'Poptávka z Prospekta'} · {date(l.updatedAt)}</p></div><strong>{czk(l.valueCzk)}</strong><label><span className="sr-only">Stav leadu {l.title}</span><select value={l.stage} disabled={busy} onChange={e=>void act({action:'stage',id:l.id,stage:e.target.value})}>{Object.entries(stageLabels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label></article>)}</div>:<EmptyState title="Zatím žádné leady.">Projevte zájem o poptávku nebo si přidejte vlastní obchodní příležitost.</EmptyState>;
  }
  const pipeline=<section className="m-section"><div className="m-section-heading"><h2>Pipeline</h2><Link href={href('crm')}>Otevřít CRM <ArrowUpRight size={15}/></Link></div><div className="m-pipeline">{Object.entries(stageLabels).map(([stage,label])=><div key={stage} className="m-pipeline-column"><h3>{label}<span>{state.leads.filter(l=>l.stage===stage).length}</span></h3>{state.leads.filter(l=>l.stage===stage).slice(0,5).map(l=><article key={l.id}><strong>{l.title}</strong><small>{czk(l.valueCzk)}</small><label><span className="sr-only">Stav {l.title}</span><select value={l.stage} disabled={busy} onChange={e=>void act({action:'stage',id:l.id,stage:e.target.value as Stage})}>{Object.entries(stageLabels).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label></article>)}{!state.leads.some(l=>l.stage===stage)&&<p>Žádné příležitosti</p>}</div>)}</div></section>;
  const tasks=<section className="m-section"><div className="m-section-heading"><h2>Úkoly</h2><Link href={href('kalendar')}>Kalendář <ArrowUpRight size={15}/></Link></div><div className="p-card m-records">{state.tasks.filter(t=>!t.done).slice(0,10).map(t=><label className="m-task" key={t.id}><input type="checkbox" checked={!!t.done} disabled={busy} onChange={e=>void act({action:'task-done',id:t.id,done:e.target.checked})}/><span>{t.title}</span><small>{t.dueAt?date(t.dueAt):'Bez termínu'}</small></label>)}{!state.tasks.some(t=>!t.done)&&<p>Vše vyřízeno. Přidejte si další krok k nové zakázce.</p>}<form className="m-inline-form" onSubmit={e=>void submit(e,v=>({action:'task',title:v.title,dueAt:null}))}><input name="title" aria-label="Nový úkol" placeholder="Např. Zavolat Jan Novák" minLength={2} maxLength={300} required/><PanelButton disabled={busy} type="submit"><Plus size={16}/> Přidat úkol</PanelButton></form></div></section>;
  const stats=<div className="m-stats">{[[state.summary.newLeads,'Nové leady'],[state.summary.activeLeads,'Aktivní leady'],[state.summary.offers,'Nabídky'],[state.summary.won,'Vyhrané zakázky'],[czk(state.summary.pipelineValue),'Hodnota pipeline']].map(([number,label])=><article className="p-card" key={label}><span>{label}</span><strong>{number}</strong></article>)}</div>;
  const title=nav.find(([id])=>id===view)?.[1]??(view==='nova-poptavka'?'Vytvořit poptávku':'Nabídky zákazníkům');
  return <div className="p-app m-app"><a className="skip-link" href="#market-content">Přejít na obsah</a><aside className="p-sidebar m-sidebar"><div className="p-sidebar-brand"><Logo plain/></div><nav aria-label={customer?'Zákaznické prostředí':'Prostředí dodavatele'}>{nav.map(([id,label,Icon])=><Link key={id} href={href(id)} className={view===id?'active':''} aria-current={view===id?'page':undefined}><Icon size={19}/>{label}</Link>)}</nav><div className="p-workspace-card"><span>{typeLabels[account.type!]}</span><strong>{account.name}</strong>{!customer&&<Link href="/nastroje/">Databáze firem a kampaně ↗</Link>}</div><LogoutButton className="p-sidebar-exit"><LogOut size={16}/> Odhlásit se</LogoutButton></aside><div className="p-main"><header className="p-topbar m-topbar"><AccountSwitcher context={context}/><div className="m-person"><span className="p-avatar">{name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><strong>{name}</strong></div></header><nav className="m-mobile-nav" aria-label="Mobilní navigace">{nav.map(([id,label])=><Link key={id} href={href(id)} aria-current={view===id?'page':undefined}>{label}</Link>)}</nav><main className="p-content m-content" id="market-content"><div className="p-heading"><div><span className="m-eyebrow">{customer?'Vaše Prospekto':account.type==='COMPANY'?'Firemní prostředí':'Prostor pro vaše podnikání'}</span><h1>{view==='prehled'?'Dobrý den, '+name.split(' ')[0]+'.':title}</h1><p>{view==='prehled'?(customer?'Najděte správné lidi pro svůj další projekt.':'Nové příležitosti a rozpracované zakázky na jednom místě.'):account.name}</p></div>{customer?<Link className="p-button" href={href('nova-poptavka')}><Plus size={18}/> Vytvořit poptávku</Link>:<Link className="p-button" href={href('poptavky')}>Prohlédnout poptávky <ArrowUpRight size={17}/></Link>}</div>
    {error&&<p className="p-error m-notice" role="alert">{error}</p>}{notice&&<p className="m-success m-notice" role="status"><Check size={16}/>{notice}</p>}
    {view==='prehled'&&customer&&<><section className="m-customer-hero"><span className="m-eyebrow">Od nápadu k hotové práci</span><h2>Co pro vás můžeme<br/>pomoci zařídit?</h2><p>Popište svůj projekt a vyberte si dodavatele podle nabídky, zkušeností a referencí.</p><Link className="p-button" href={href('nova-poptavka')}>Vytvořit poptávku <Plus size={18}/></Link></section><div className="m-stats">{[[state.requests.filter(r=>r.status==='OPEN').length,'Otevřené poptávky'],[state.offers.filter(o=>o.status==='SENT').length,'Nabídky od firem'],[state.messages.length,'Zprávy']].map(([value,label])=><article className="p-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="m-section"><div className="m-section-heading"><h2>Moje poptávky</h2><Link href={href('poptavky')}>Zobrazit všechny ↗</Link></div>{requestCards(state.requests.slice(0,3))}</section></>}
    {view==='prehled'&&!customer&&<>{stats}<section className="m-section"><div className="m-section-heading"><h2>Nové poptávky</h2><Link href={href('poptavky')}>Zobrazit všechny ↗</Link></div>{requestCards(state.requests.filter(r=>!state.leads.some(l=>l.requestId===r.id)).slice(0,3))}</section>{pipeline}<div className="m-dashboard-columns">{tasks}<section className="m-section"><div className="m-section-heading"><h2>Aktivní leady</h2><Link href={href('leady')}>Všechny leady ↗</Link></div>{leadCards(state.leads.filter(l=>!['WON','LOST'].includes(l.stage)).slice(0,4))}</section></div></>}
    {view==='poptavky'&&<><div className="m-filters"><input aria-label="Hledat poptávku" placeholder="Hledat podle názvu nebo města" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Obor" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Všechny obory</option>{services.filter(s=>!s.parentId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Kraj" value={region} onChange={e=>setRegion(e.target.value)}><option value="">Všechny kraje</option>{CZECH_REGIONS.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></div>{requestCards(state.requests.filter(r=>(!search||normalizeSearch(r.title+' '+r.city).includes(normalizeSearch(search)))&&(!region||r.region===region)&&(!category||r.serviceId===category||services.some(s=>s.id===r.serviceId&&s.parentId===category))))}</>}
    {view==='nova-poptavka'&&customer&&<form className="p-card p-form m-form-card" onSubmit={e=>void submit(e,v=>({action:'request',...v,budgetCzk:v.budgetCzk?Number(v.budgetCzk):null}))}><Field label="Název poptávky"><input name="title" placeholder="Např. Rekonstrukce koupelny v Ostravě" minLength={3} maxLength={160} required/></Field><Field label="Co potřebujete?"><textarea name="description" placeholder="Popište rozsah práce, očekávaný termín a další důležité podrobnosti." minLength={10} maxLength={5000} rows={6} required/></Field><Field label="Služba"><select name="serviceId" required defaultValue=""><option value="" disabled>Vyberte službu</option>{services.filter(s=>!s.parentId).map(root=><optgroup key={root.id} label={root.name}>{[root,...services.filter(s=>s.parentId===root.id)].map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</optgroup>)}</select></Field><div className="m-form-grid"><Field label="Město"><input name="city" maxLength={160} required/></Field><Field label="Kraj"><select name="region" required defaultValue=""><option value="" disabled>Vyberte kraj</option>{CZECH_REGIONS.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></Field></div><Field label="Rozpočet v Kč (volitelně)"><input name="budgetCzk" type="number" min={0} max={1000000000}/></Field><PanelButton disabled={busy} type="submit">Zveřejnit poptávku</PanelButton><Link href={href('poptavky')}>Přejít na moje poptávky →</Link></form>}
    {(view==='leady'||view==='crm')&&!customer&&<>{view==='crm'?pipeline:leadCards(state.leads)}<form className="p-card p-form m-form-card m-section" onSubmit={e=>void submit(e,v=>({action:'lead',...v,valueCzk:Number(v.valueCzk)}))}><h2>Nová obchodní příležitost</h2><Field label="Název"><input name="title" minLength={2} maxLength={160} required/></Field><Field label="Kontakt"><input name="contactName" maxLength={160}/></Field><Field label="Odhadovaná hodnota v Kč"><input name="valueCzk" type="number" min={0} max={1000000000} defaultValue={0} required/></Field><PanelButton disabled={busy} type="submit">Přidat lead</PanelButton></form><Link className="p-button p-secondary" href={href('nabidky')}>Připravit nabídku zákazníkovi</Link></>}
    {view==='zakazky'&&!customer&&<>{leadCards(state.leads.filter(l=>l.stage==='WON'))}<Link className="p-button p-secondary m-section" href={href('nabidky')}>Nabídky zákazníkům</Link></>}
    {view==='kalendar'&&!customer&&<>{tasks}<form className="p-card p-form m-form-card" onSubmit={e=>void submit(e,v=>({action:'task',title:v.title,dueAt:v.dueAt?new Date(v.dueAt).toISOString():null}))}><h2>Naplánovat úkol</h2><Field label="Co je potřeba udělat?"><input name="title" minLength={2} maxLength={300} required/></Field><Field label="Termín"><input name="dueAt" type="datetime-local" required/></Field><PanelButton disabled={busy} type="submit">Uložit do kalendáře</PanelButton></form><section className="m-section m-records">{state.tasks.filter(t=>t.dueAt).sort((a,b)=>a.dueAt!.localeCompare(b.dueAt!)).map(t=><article className="p-card m-lead" key={t.id}><strong>{t.title}</strong><p>{new Date(t.dueAt!).toLocaleString('cs-CZ')} · {t.done?'Dokončeno':'Čeká'}</p></article>)}</section></>}
    {view==='statistiky'&&!customer&&<>{stats}{pipeline}</>}
    {view==='nabidky'&&<><div className="m-records">{state.offers.map(o=><article className="p-card m-request-card" key={o.id}><div className="m-card-meta"><h3>{o.requestTitle}</h3><span className="p-badge">{offerStatus[o.status]}</span></div><strong>{o.providerName} · {czk(o.amountCzk)}</strong><p className="m-prewrap">{o.body}</p>{customer&&o.status==='SENT'&&state.requests.some(r=>r.id===o.requestId&&r.status==='OPEN')&&<PanelButton disabled={busy} onClick={()=>void act({action:'accept-offer',id:o.id})}>Vybrat tohoto dodavatele</PanelButton>}</article>)}</div>{!state.offers.length&&<EmptyState title="Nabídky jsou zatím prázdné.">{customer?'Jakmile dodavatelé pošlou nabídku k vaší poptávce, najdete ji tady.':'Vyberte poptávku ze svých leadů a připravte nabídku.'}</EmptyState>}{!customer&&<form className="p-card p-form m-form-card m-section" onSubmit={e=>void submit(e,v=>({action:'offer',...v,amountCzk:Number(v.amountCzk)}))}><h2>Nová nabídka</h2><Field label="Poptávka"><select name="requestId" required defaultValue=""><option value="" disabled>Vyberte poptávku</option>{state.threads.map(t=><option key={t.requestId} value={t.requestId}>{t.requestTitle}</option>)}</select></Field><Field label="Nabídka zákazníkovi"><textarea name="body" rows={5} minLength={5} maxLength={5000} required/></Field><Field label="Cena v Kč"><input name="amountCzk" type="number" min={0} max={1000000000} required/></Field><PanelButton disabled={busy||!state.threads.length} type="submit">Odeslat nabídku</PanelButton></form>}</>}
    {view==='zpravy'&&<><form className="p-card p-form m-form-card" onSubmit={e=>void submit(e,v=>{const [requestId,providerId]=thread.split('|');return {action:'message',requestId,providerId,body:v.body};})}><Field label="Konverzace"><select value={thread} onChange={e=>setThread(e.target.value)} required><option value="">Vyberte poptávku a dodavatele</option>{state.threads.map(t=><option key={t.requestId+t.providerId} value={t.requestId+'|'+t.providerId}>{t.requestTitle} · {t.providerName}</option>)}</select></Field><Field label="Zpráva"><textarea name="body" maxLength={5000} rows={4} required/></Field><PanelButton type="submit" disabled={busy||!thread}>Odeslat zprávu</PanelButton></form><div className="m-records m-section">{state.messages.filter(m=>!thread||m.requestId+'|'+m.providerId===thread).map(m=><article className={'p-card m-message '+(m.senderAccountId===account.id?'own':'')} key={m.id}><div className="m-card-meta"><strong>{m.senderName}</strong><small>{new Date(m.createdAt).toLocaleString('cs-CZ')}</small></div><p className="m-prewrap">{m.body}</p></article>)}</div>{!state.messages.length&&<EmptyState title="Místo pro společnou domluvu.">Konverzace vznikne, jakmile dodavatel projeví zájem o poptávku.</EmptyState>}</>}
    {(view==='dodavatele'||view==='oblibeni')&&customer&&<><div className="m-filters"><input aria-label="Hledat dodavatele" placeholder="Jméno, služba nebo město" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="m-card-grid">{state.providers.filter(p=>(view!=='oblibeni'||p.favorite)&&normalizeSearch(p.name+' '+p.city+' '+p.serviceNames).includes(normalizeSearch(search))).map(p=><article className="p-card m-provider-card" key={p.id}>{p.avatarUrl&&<img src={p.avatarUrl} alt="" width={64} height={64}/>}<h3><Link href={'/dodavatele/'+p.id+'/'}>{p.name} ↗</Link></h3><p>{p.city} · {p.serviceNames}</p><p className="m-clamp">{p.description||'Dodavatel si zatím nedoplnil představení.'}</p>{p.website&&<a href={p.website} target="_blank" rel="noreferrer" className="m-text-button">Web dodavatele ↗</a>}<button className="p-button p-secondary" disabled={busy} onClick={()=>void act({action:'favorite',providerId:p.id,enabled:!p.favorite})}><Heart size={17} fill={p.favorite?'currentColor':'none'}/>{p.favorite?'Odebrat z oblíbených':'Uložit dodavatele'}</button></article>)}</div>{!state.providers.some(p=>(view!=='oblibeni'||p.favorite)&&normalizeSearch(p.name+' '+p.city+' '+p.serviceNames).includes(normalizeSearch(search)))&&<EmptyState title="Zatím žádní dodavatelé v tomto výběru.">Vyzkoušejte jiný hledaný výraz nebo vytvořte poptávku.</EmptyState>}</>}
    {view==='recenze'&&customer&&<><div className="m-records">{state.reviews.map(r=><article className="p-card" key={r.id}><h3>{r.providerName} · {r.rating}/5</h3><p>{r.body}</p></article>)}</div>{!state.reviews.length&&<EmptyState title="Vaše zkušenost pomůže ostatním.">Po dokončení poptávky můžete ohodnotit vybraného dodavatele.</EmptyState>}<form className="p-card p-form m-form-card m-section" onSubmit={e=>void submit(e,v=>({action:'review',...v,rating:Number(v.rating)}))}><Field label="Dokončená poptávka"><select name="requestId" required defaultValue=""><option value="">Vyberte dokončenou zakázku</option>{state.requests.filter(r=>r.status==='CLOSED'&&state.offers.some(o=>o.requestId===r.id&&o.status==='ACCEPTED')).map(r=><option value={r.id} key={r.id}>{r.title}</option>)}</select></Field><Field label="Hodnocení"><select name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} z 5</option>)}</select></Field><Field label="Vaše zkušenost"><textarea name="body" rows={4} minLength={3} maxLength={3000} required/></Field><PanelButton type="submit" disabled={busy}>Přidat recenzi</PanelButton></form></>}
    {view==='profil'&&profile&&<section className="p-card m-profile">{profile.profile.coverUrl&&<img className="m-cover" src={profile.profile.coverUrl} alt="Titulní fotografie"/>}<div className="m-section-heading"><div>{profile.profile.avatarUrl&&<img className="m-profile-avatar" src={profile.profile.avatarUrl} alt="" width={96} height={96}/>}<h2>{account.name}</h2><p>{profile.area.city} · dojezd {profile.area.maxDistanceKm} km</p></div>{canManage(account.role)&&<Link className="p-button p-secondary" href="/onboarding/?edit=1&step=5">Upravit profil</Link>}</div><p className="m-prewrap">{profile.profile.description||'Doplňte představení a ukažte zákazníkům, s čím jim pomůžete.'}</p><p>{profile.services.serviceIds.map(id=>services.find(s=>s.id===id)?.name).filter(Boolean).join(' · ')}</p><p>{profile.profile.experience}</p>{profile.profile.website&&<a href={profile.profile.website} rel="noreferrer" target="_blank">Web ↗</a>}<div className="m-portfolio-edit">{profile.profile.portfolio.map((p,i)=><figure key={i}><img src={p.imageUrl} alt={p.title||'Realizace'}/><figcaption>{p.title}</figcaption></figure>)}</div><h3>Reference</h3><p className="m-prewrap">{profile.profile.referencesText}</p>{state.reviews.map(r=><article className="m-review" key={r.id}><strong>{r.rating}/5</strong><p>{r.body}</p></article>)}</section>}
    {view==='nastaveni'&&<div className="m-card-grid"><section className="p-card m-request-card"><h2>Nastavení účtu</h2><p>{name}<br/>{typeLabels[account.type!]} · {account.name}</p>{canManage(account.role)?<Link className="p-button p-secondary" href="/onboarding/?edit=1&step=1">Upravit údaje a profil</Link>:<p>Firemní profil upravuje vlastník nebo administrátor.</p>}<Link href="/onboarding/?new=1" className="m-text-button">Přidat jiný typ účtu →</Link></section>{!customer&&<section className="p-card m-request-card"><h2>Vaše obchodní nástroje</h2><p>Databáze firem, uložené seznamy, kampaně a nastavení e-mailového bota.</p><Link className="p-button p-secondary" href="/nastroje/">Otevřít nástroje</Link></section>}{account.type==='COMPANY'&&canManage(account.role)&&<section className="p-card m-request-card"><h2>Členové firmy</h2>{team.map(m=><div key={m.email}><strong>{m.name}</strong><p>{m.email} · {({COMPANY_OWNER:'Vlastník',COMPANY_ADMIN:'Administrátor',COMPANY_MEMBER:'Člen týmu'} as Record<string,string>)[m.role]??m.role}</p></div>)}<p>Správa pozvánek členů týmu bude doplněna v další verzi.</p></section>}</div>}
  </main></div></div>;
}
