'use client';
import {useState,type FormEvent,type ReactNode} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Messenger} from '@/components/messenger/messenger';
import {RequestBrowser} from './request-browser';
import {OfferDialog} from './offer-dialog';
import {LayoutDashboard,FileText,GitBranch,MessageSquare,BriefcaseBusiness,CalendarDays,UserRound,BarChart3,Settings,Heart,Star,Search,Plus,ArrowUpRight,Check,LogOut} from 'lucide-react';
import {Logo} from '@/components/prospekto/logo';
import {LogoutButton} from '@/components/panel/logout-button';
import {Field,PanelButton,Empty} from '@/components/panel/ui';
import {AccountSwitcher} from '@/components/accounts/account-switcher';
import {CalendarView} from './calendar-view';
import {canManage,destination,typeLabels,type AccountContext,type OnboardingData,type Service} from '@/lib/accounts/model';
import {CZECH_REGIONS,normalizeSearch,regionLabel} from '@/lib/company-types';
import {cooperationLabels,requesterLabels,type MarketplaceState,type MarketRequest,type Offer} from '@/lib/marketplace/model';

const providerNav=[['prehled','Přehled',LayoutDashboard],['poptavky','Hledat zakázky',Search],['moje-poptavky','Moje poptávky',FileText],['prijate-nabidky','Nabídky k poptávkám',BriefcaseBusiness],['crm','CRM',GitBranch],['nabidky','Odeslané nabídky',BriefcaseBusiness],['zpravy','Zprávy',MessageSquare],['zakazky','Zakázky',BriefcaseBusiness],['kalendar','Kalendář',CalendarDays],['dodavatele','Hledat dodavatele',Search],['oblibeni','Oblíbení dodavatelé',Heart],['recenze','Moje recenze',Star],['profil','Profil',UserRound],['statistiky','Statistiky',BarChart3],['nastaveni','Nastavení',Settings]] as const;
const customerNav=[['prehled','Přehled',LayoutDashboard],['poptavky','Moje poptávky',FileText],['nabidky','Nabídky od firem',BriefcaseBusiness],['zpravy','Zprávy',MessageSquare],['dodavatele','Hledat dodavatele',Search],['oblibeni','Oblíbení dodavatelé',Heart],['recenze','Moje recenze',Star],['nastaveni','Nastavení účtu',Settings]] as const;
const czk=(value:number)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(value);
const date=(value:string)=>new Date(value).toLocaleDateString('cs-CZ');
const requestStatus:Record<string,string>={OPEN:'Otevřená',ASSIGNED:'Dodavatel vybraný',CLOSED:'Dokončená'};
const offerStatus:Record<string,string>={SENT:'Odeslaná',ACCEPTED:'Přijatá',REJECTED:'Nepřijatá'};
const EmptyState=({title,children,action}:{title:string;children:ReactNode;action?:ReactNode})=><Empty title={title} action={action}>{children}</Empty>;
export function Dashboard({context,initial,view,name,services,profile,team}:{context:AccountContext;initial:MarketplaceState;view:string;name:string;services:Service[];profile:OnboardingData|null;team:{name:string;email:string;role:string}[]}) {
  const account=context.account!,customer=account.type==='CUSTOMER',base=destination(context);
  const nav=customer?customerNav:providerNav;
  const href=(section:string)=>base+(section==='prehled'?'':section+'/');
  const [state,setState]=useState(initial),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[region,setRegion]=useState('');
  const router=useRouter();
  const [offerRequest,setOfferRequest]=useState<{id:string;title:string}|null>(null);
  function openChat(requestId:string,providerId?:string){const thread=state.threads.find(t=>t.requestId===requestId&&(!providerId||t.providerId===providerId));if(thread)router.push(href('zpravy')+'?contact='+encodeURIComponent(thread.customerId===account.id?thread.providerId:thread.customerId));else setError('Kontakt zatím není dostupný. Obnovte stránku a zkuste to znovu.');}
  async function act(body:unknown):Promise<boolean> {
    if(busy)return false;setBusy(true);setError('');setNotice('');
    try {
      const response=await fetch('/api/marketplace/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
      const result=await response.json();if(!response.ok)throw new Error(result.error||'Změnu se nepodařilo uložit.');
      setState(result.state);const action=(body as {action?:string}).action;setNotice(({offer:'Nabídka byla zdarma odeslána. Po přijetí zákazníkem můžete odemknout chat za 49 kreditů.','unlock-chat':'Chat je odemknutý. Další zprávy jsou zdarma.',request:'Hotovo, poptávka je zveřejněná. Nabídky od dodavatelů najdete u svých poptávek.','accept-offer':'Nabídka byla přijata. Jakmile dodavatel odemkne chat, můžete se domluvit ve Zprávách.'} as Record<string,string>)[action??'']??'Hotovo, změny jsou uložené.');return true;
    }catch(error){setError(error instanceof Error?error.message:'Zkuste to znovu.');return false;}finally{setBusy(false);}
  }
  async function submit(event:FormEvent<HTMLFormElement>,build:(values:Record<string,string>)=>unknown) {
    event.preventDefault();const form=event.currentTarget;
    const values=Object.fromEntries(new FormData(form)) as Record<string,string>;
    if(await act(build(values)))form.reset();
  }
  function requestCards(items:MarketRequest[],owned=customer) {
    return items.length?<div className="m-card-grid">{items.map(r=><article className="p-card m-request-card" key={r.id}><div className="m-card-meta"><span className="p-badge">{services.find(s=>s.id===r.serviceId)?.name}</span><small>{date(r.createdAt)}</small></div><h3>{r.title}</h3><div className="m-request-labels"><span className="p-badge">{requesterLabels[r.requesterType]}</span><span className="p-badge">{cooperationLabels[r.cooperationType]}</span></div><p className="m-clamp">{r.description}</p><p>{r.city} · {regionLabel(r.region)}</p><div className="m-card-meta"><strong>{r.budgetCzk===null?'Rozpočet dohodou':czk(r.budgetCzk)}</strong><span className="p-badge">{requestStatus[r.status]}</span></div>{r.requesterId===account.id?<div className="m-form-actions"><Link className="p-button p-secondary" href={href(customer?'nabidky':'prijate-nabidky')}>Zobrazit nabídky</Link>{r.status!=='CLOSED'&&<button className="m-text-button" disabled={busy} onClick={()=>void act({action:'close-request',id:r.id})}>Označit dokončené</button>}</div>:<div className="m-form-actions"><button className="p-button" disabled={busy} onClick={()=>setOfferRequest(r)}>Poslat nabídku zdarma <ArrowUpRight size={16}/></button></div>}</article>)}</div>:<EmptyState title={owned?'Vaše první poptávka začíná tady.':'Zatím tu nejsou odpovídající poptávky.'} action={owned?<Link className="p-button" href={href('nova-poptavka')}>Vytvořit poptávku</Link>:<Link className="p-button p-secondary" href="/onboarding/?edit=1&step=3">Upravit služby a oblast</Link>}>{owned?'Popište, s čím potřebujete pomoci. Dodavatelé vám mohou poslat nabídku.':'Nové poptávky se zobrazí podle vašich služeb, měst a vybraných krajů.'}</EmptyState>;
  }
  function offerCards(items:Offer[],asRequester=customer) {
    return <div className="m-records">{items.map(o=><article className="p-card m-request-card" key={o.id}>
      <div className="m-card-meta"><h3>{o.requestTitle}</h3><span className="p-badge">{offerStatus[o.status]}</span></div>
      <strong>{o.providerName} · {czk(o.amountCzk)}</strong><p className="m-prewrap">{o.body}</p>
      {asRequester&&o.status==='SENT'&&state.ownRequests.some(r=>r.id===o.requestId&&r.status==='OPEN')&&<PanelButton disabled={busy} onClick={()=>void act({action:'accept-offer',id:o.id})}>Přijmout nabídku</PanelButton>}
      {o.chatUnlocked?<button className="p-button p-secondary" onClick={()=>openChat(o.requestId,o.providerId)}>{asRequester?'Napsat dodavateli':'Napsat zákazníkovi'} →</button>
        :o.status==='ACCEPTED'?asRequester?<p>Čekáme, až dodavatel odemkne chat. Pro vás je komunikace zdarma.</p>:<><p>Nabídka je přijatá. Odemknutí této konverzace stojí jednorázově 49 kreditů. Další zprávy jsou zdarma.</p><PanelButton disabled={busy||state.credits<49} onClick={async()=>{if(await act({action:'unlock-chat',id:o.id}))openChat(o.requestId,o.providerId);}}>Odemknout chat · 49 kreditů</PanelButton>{state.credits<49&&<p className="p-error">Nedostatek kreditů. Potřebujete alespoň 49 kreditů.</p>}</>
        :<p>{o.status==='SENT'?'Chat bude dostupný po přijetí nabídky zákazníkem a odemknutí dodavatelem.':'Tato nabídka nebyla přijata.'}</p>}
    </article>)}</div>;
  }
  const pipeline=<section className="m-section"><h2>Přehled nabídek</h2><div className="m-pipeline">{Object.entries(offerStatus).map(([status,label])=><div key={status} className="m-pipeline-column"><h3>{label}<span>{state.offers.filter(o=>o.status===status).length}</span></h3>{state.offers.filter(o=>o.status===status).slice(0,5).map(o=><article key={o.id}><strong>{o.requestTitle}</strong><small>{czk(o.amountCzk)}</small><Link href={href('nabidky')}>Zobrazit nabídku →</Link></article>)}</div>)}</div></section>;
  const tasks=<section className="m-section"><div className="m-section-heading"><h2>Úkoly</h2><Link href={href('kalendar')}>Kalendář <ArrowUpRight size={15}/></Link></div><div className="p-card m-records">{state.tasks.filter(t=>!t.done).slice(0,10).map(t=><label className="m-task" key={t.id}><input type="checkbox" checked={!!t.done} disabled={busy} onChange={e=>void act({action:'task-done',id:t.id,done:e.target.checked})}/><span>{t.title}</span><small>{t.dueAt?date(t.dueAt):'Bez termínu'}</small></label>)}{!state.tasks.some(t=>!t.done)&&<p>Vše vyřízeno. Přidejte si další krok k nové zakázce.</p>}<form className="m-inline-form" onSubmit={e=>void submit(e,v=>({action:'task',title:v.title,dueAt:null}))}><input name="title" aria-label="Nový úkol" placeholder="Např. Zavolat Jan Novák" minLength={2} maxLength={300} required/><PanelButton disabled={busy} type="submit"><Plus size={16}/> Přidat úkol</PanelButton></form></div></section>;
  const stats=<div className="m-stats">{[[state.offers.filter(o=>o.status==='SENT').length,'Čekají na přijetí'],[state.offers.length,'Odeslané nabídky'],[state.offers.filter(o=>o.status==='ACCEPTED').length,'Přijaté nabídky'],[state.credits.toLocaleString('cs-CZ'),'Kredity']].map(([number,label])=><article className="p-card" key={label}><span>{label}</span><strong>{number}</strong></article>)}</div>;
  const title=nav.find(([id])=>id===view)?.[1]??(view==='nova-poptavka'?'Vytvořit poptávku':'Nabídky zákazníkům');
  return <div className="p-app m-app"><a className="skip-link" href="#market-content">Přejít na obsah</a><aside className="p-sidebar m-sidebar"><div className="p-sidebar-brand"><Logo plain/></div><nav aria-label={customer?'Zákaznické prostředí':'Prostředí dodavatele'}>{nav.map(([id,label,Icon])=><Link key={id} href={href(id)} className={view===id?'active':''} aria-current={view===id?'page':undefined}><Icon size={19}/>{label}</Link>)}{customer?<Link href="/moje-reakce/"><FileText size={19}/>Moje reakce na práci</Link>:canManage(account.role)&&<Link href="/zamestnavatel/prace/"><BriefcaseBusiness size={19}/>Správa náboru</Link>}</nav><div className="p-workspace-card"><span>{typeLabels[account.type!]}</span><strong>{account.name}</strong>{!customer&&<Link href="/nastroje/">Databáze firem a kampaně ↗</Link>}</div><LogoutButton className="p-sidebar-exit"><LogOut size={16}/> Odhlásit se</LogoutButton></aside><div className="p-main"><header className="p-topbar m-topbar"><AccountSwitcher context={context}/>{!customer&&<span className="p-badge m-credit-balance" aria-label="Zůstatek kreditů">{state.credits.toLocaleString('cs-CZ')} kreditů · demo</span>}<div className="m-person"><span className="p-avatar">{name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><strong>{name}</strong></div></header><nav className="m-mobile-nav" aria-label="Mobilní navigace">{nav.map(([id,label])=><Link key={id} href={href(id)} aria-current={view===id?'page':undefined}>{label}</Link>)}<Link href={customer?"/moje-reakce/":"/zamestnavatel/prace/"}>{customer?"Moje reakce":"Správa náboru"}</Link></nav><main className="p-content m-content" id="market-content"><div className="p-heading"><div><span className="m-eyebrow">{customer?'Vaše Prospekto':'Prostor pro vaše podnikání'}</span><h1>{view==='prehled'?'Dobrý den, '+name.split(' ')[0]+'.':title}</h1>{view!=='kalendar'&&<p>{view==='prehled'?(customer?'Najděte správné lidi pro svůj další projekt.':'Nové příležitosti a rozpracované zakázky na jednom místě.'):account.name}</p>}</div>{view!=='zpravy'&&view!=='kalendar'&&<div className="m-form-actions">{!customer&&<Link className="p-button p-secondary" href={href('poptavky')}>Hledat zakázky <ArrowUpRight size={17}/></Link>}<Link className="p-button" href={href('nova-poptavka')}><Plus size={18}/> Vytvořit poptávku</Link></div>}</div>
    {error&&<p className="p-error m-notice" role="alert">{error}</p>}{notice&&<p className="m-success m-notice" role="status"><Check size={16}/>{notice}</p>}
    {view==='prehled'&&customer&&<><section className="m-customer-hero"><span className="m-eyebrow">Od nápadu k hotové práci</span><h2>Co pro vás můžeme<br/>pomoci zařídit?</h2><p>Popište svůj projekt a vyberte si dodavatele podle nabídky, zkušeností a referencí.</p><Link className="p-button" href={href('nova-poptavka')}>Vytvořit poptávku <Plus size={18}/></Link></section><div className="m-stats">{[[state.requests.filter(r=>r.status==='OPEN').length,'Otevřené poptávky'],[state.offers.filter(o=>o.status==='SENT').length,'Nabídky od firem'],[state.messages.length,'Zprávy']].map(([value,label])=><article className="p-card" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="m-section"><div className="m-section-heading"><h2>Moje poptávky</h2><Link href={href('poptavky')}>Zobrazit všechny ↗</Link></div>{requestCards(state.requests.slice(0,3))}</section></>}
    {view==='prehled'&&!customer&&<>{stats}<section className="p-card m-section"><h2>Hledejte zakázky i spolupracovníky</h2><p>Pošlete nabídku na práci pro sebe, nebo zadejte vlastní poptávku po dodavateli či dlouhodobé spolupráci na IČO.</p><div className="m-form-actions"><Link href={href('moje-poptavky')} className="p-button p-secondary">Moje poptávky · {state.ownRequests.length}</Link><Link href={href('prijate-nabidky')} className="p-button p-secondary">Nabídky k poptávkám · {state.receivedOffers.filter(o=>o.status==='SENT').length}</Link></div></section><section className="m-section"><div className="m-section-heading"><h2>Nové poptávky</h2><Link href={href('poptavky')}>Zobrazit všechny ↗</Link></div>{requestCards(state.requests.filter(r=>!state.offers.some(o=>o.requestId===r.id)).slice(0,3))}</section>{pipeline}{tasks}</>}
    {view==='poptavky'&&!customer&&<RequestBrowser services={services} offers={state.offers} busy={busy} onOffer={setOfferRequest}/>}
    {(view==='poptavky'&&customer||view==='moje-poptavky')&&<><div className="m-filters"><input aria-label="Hledat poptávku" placeholder="Hledat podle názvu nebo města" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Obor" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Všechny obory</option>{services.filter(s=>!s.parentId).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Kraj" value={region} onChange={e=>setRegion(e.target.value)}><option value="">Všechny kraje</option>{CZECH_REGIONS.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></div>{requestCards(state.ownRequests.filter(r=>(!search||normalizeSearch(r.title+' '+r.city).includes(normalizeSearch(search)))&&(!region||r.region===region)&&(!category||r.serviceId===category||services.some(s=>s.id===r.serviceId&&s.parentId===category))),true)}</>}
    {view==='nova-poptavka'&&<form className="p-card p-form m-form-card" onSubmit={e=>void submit(e,v=>({action:'request',...v,budgetCzk:v.budgetCzk?Number(v.budgetCzk):null}))}><p>Poptávka bude označená jako <strong>{requesterLabels[account.type!]}</strong>. Typ zadavatele se určuje podle vašeho účtu.</p><Field label="Typ spolupráce"><select name="cooperationType" defaultValue="ONE_OFF">{Object.entries(cooperationLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Název poptávky"><input name="title" placeholder="Např. Rekonstrukce koupelny nebo hledáme elektrikáře na IČO" minLength={3} maxLength={160} required/></Field><Field label="Co potřebujete?"><textarea name="description" placeholder="Popište rozsah práce, očekávaný termín a další důležité podrobnosti." minLength={10} maxLength={5000} rows={6} required/></Field><Field label="Služba"><select name="serviceId" required defaultValue=""><option value="" disabled>Vyberte službu</option>{services.filter(s=>!s.parentId).map(root=><optgroup key={root.id} label={root.name}>{[root,...services.filter(s=>s.parentId===root.id)].map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</optgroup>)}</select></Field><div className="m-form-grid"><Field label="Město"><input name="city" maxLength={160} required/></Field><Field label="Kraj"><select name="region" required defaultValue=""><option value="" disabled>Vyberte kraj</option>{CZECH_REGIONS.map(r=><option value={r.id} key={r.id}>{r.label}</option>)}</select></Field></div><Field label="Rozpočet v Kč (volitelně)"><input name="budgetCzk" type="number" min={0} max={1000000000}/></Field><PanelButton disabled={busy} type="submit">Zveřejnit poptávku</PanelButton><Link href={href(customer?'poptavky':'moje-poptavky')}>Přejít na moje poptávky →</Link></form>}
    {view==='crm'&&!customer&&<>{pipeline}<Link className="p-button" href={href('nabidky')}>Spravovat nabídky</Link></>}
    {view==='zakazky'&&!customer&&<>{offerCards(state.offers.filter(o=>o.status==='ACCEPTED'))}{!state.offers.some(o=>o.status==='ACCEPTED')&&<EmptyState title="Zatím žádné přijaté nabídky.">Pošlete nabídku zdarma z přehledu poptávek.</EmptyState>}</>}
    {view==='kalendar'&&!customer&&<CalendarView tasks={state.tasks} busy={busy} onCreate={(title,dueAt)=>act({action:'task',title,dueAt})} onToggle={(id,done)=>act({action:'task-done',id,done})}/>}
    {view==='statistiky'&&!customer&&<>{stats}{pipeline}</>}
    {view==='nabidky'&&<><p className="m-help">{customer?'Vyberte si nabídku a potvrďte ji. Chat zpřístupní dodavatel; vy nic neplatíte.':'Nabídky posíláte zdarma. Po přijetí zákazníkem odemknete společný chat jednorázově za 49 kreditů.'}</p>{offerCards(state.offers)}{!state.offers.length&&<EmptyState title="Nabídky jsou zatím prázdné.">{customer?'Jakmile dodavatelé pošlou nabídku k vaší poptávce, najdete ji tady.':'Otevřete Poptávky a u vybrané poptávky klikněte na Poslat nabídku zdarma.'}</EmptyState>}{!customer&&<Link className="p-button m-section" href={href('poptavky')}>Najít poptávku a poslat nabídku zdarma →</Link>}</>}
    {view==='prijate-nabidky'&&<><p className="m-help">Nabídky dodavatelů na vaše poptávky. Vyberte nabídku a potvrďte ji. Chat odemkne dodavatel za 49 kreditů, vy jako zadavatel nic neplatíte.</p>{offerCards(state.receivedOffers,true)}{!state.receivedOffers.length&&<EmptyState title="Zatím žádné nabídky k vašim poptávkám." action={<Link className="p-button" href={href('nova-poptavka')}>Vytvořit poptávku</Link>}>Zadejte zakázku nebo dlouhodobou spolupráci a počkejte na nabídky dodavatelů.</EmptyState>}</>}
    {view==='zpravy'&&<Messenger accountId={account.id} offersHref={href('nabidky')} incomingOffersHref={customer?undefined:href('prijate-nabidky')}/>}
    {(view==='dodavatele'||view==='oblibeni')&&<><div className="m-filters"><input aria-label="Hledat dodavatele" placeholder="Jméno, služba nebo město" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="m-card-grid">{state.providers.filter(p=>(view!=='oblibeni'||p.favorite)&&normalizeSearch(p.name+' '+p.city+' '+p.serviceNames).includes(normalizeSearch(search))).map(p=><article className="p-card m-provider-card" key={p.id}>{p.avatarUrl&&<img src={p.avatarUrl} alt="" width={64} height={64}/>}<h3><Link href={'/dodavatele/'+p.id+'/'}>{p.name} ↗</Link></h3><p>{p.city} · {p.serviceNames}</p><p className="m-clamp">{p.description||'Dodavatel si zatím nedoplnil představení.'}</p>{p.website&&<a href={p.website} target="_blank" rel="noreferrer" className="m-text-button">Web dodavatele ↗</a>}<Link className="p-button p-secondary" href={state.receivedOffers.some(o=>o.providerId===p.id&&o.chatUnlocked)?href('zpravy')+'?contact='+encodeURIComponent(p.id):href(customer?'nabidky':'prijate-nabidky')}><MessageSquare size={17}/>{state.receivedOffers.some(o=>o.providerId===p.id&&o.chatUnlocked)?'Napsat zprávu':'Domluva přes přijatou nabídku'}</Link><button className="m-text-button" disabled={busy} onClick={()=>void act({action:'favorite',providerId:p.id,enabled:!p.favorite})}><Heart size={17} fill={p.favorite?'currentColor':'none'}/>{p.favorite?'Odebrat z oblíbených':'Uložit dodavatele'}</button></article>)}</div>{!state.providers.some(p=>(view!=='oblibeni'||p.favorite)&&normalizeSearch(p.name+' '+p.city+' '+p.serviceNames).includes(normalizeSearch(search)))&&<EmptyState title="Zatím žádní dodavatelé v tomto výběru.">Vyzkoušejte jiný hledaný výraz nebo vytvořte poptávku.</EmptyState>}</>}
    {view==='recenze'&&<><div className="m-records">{state.givenReviews.map(r=><article className="p-card" key={r.id}><h3>{r.providerName} · {r.rating}/5</h3><p>{r.body}</p></article>)}</div>{!state.givenReviews.length&&<EmptyState title="Vaše zkušenost pomůže ostatním.">Po dokončení poptávky můžete ohodnotit vybraného dodavatele.</EmptyState>}<form className="p-card p-form m-form-card m-section" onSubmit={e=>void submit(e,v=>({action:'review',...v,rating:Number(v.rating)}))}><Field label="Dokončená poptávka"><select name="requestId" required defaultValue=""><option value="">Vyberte dokončenou zakázku</option>{state.ownRequests.filter(r=>r.status==='CLOSED'&&state.receivedOffers.some(o=>o.requestId===r.id&&o.status==='ACCEPTED')).map(r=><option value={r.id} key={r.id}>{r.title}</option>)}</select></Field><Field label="Hodnocení"><select name="rating" defaultValue="5">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} z 5</option>)}</select></Field><Field label="Vaše zkušenost"><textarea name="body" rows={4} minLength={3} maxLength={3000} required/></Field><PanelButton type="submit" disabled={busy}>Přidat recenzi</PanelButton></form></>}
    {view==='profil'&&profile&&<section className="p-card m-profile">{profile.profile.coverUrl&&<img className="m-cover" src={profile.profile.coverUrl} alt="Titulní fotografie"/>}<div className="m-section-heading"><div>{profile.profile.avatarUrl&&<img className="m-profile-avatar" src={profile.profile.avatarUrl} alt="" width={96} height={96}/>}<h2>{account.name}</h2><p>{profile.area.city} · dojezd {profile.area.maxDistanceKm} km</p></div>{canManage(account.role)&&<Link className="p-button p-secondary" href="/onboarding/?edit=1&step=5">Upravit profil</Link>}</div><p className="m-prewrap">{profile.profile.description||'Doplňte představení a ukažte zákazníkům, s čím jim pomůžete.'}</p><p>{profile.services.serviceIds.map(id=>services.find(s=>s.id===id)?.name).filter(Boolean).join(' · ')}</p><p>{profile.profile.experience}</p>{profile.profile.website&&<a href={profile.profile.website} rel="noreferrer" target="_blank">Web ↗</a>}<div className="m-portfolio-edit">{profile.profile.portfolio.map((p,i)=><figure key={i}><img src={p.imageUrl} alt={p.title||'Realizace'}/><figcaption>{p.title}</figcaption></figure>)}</div><h3>Reference</h3><p className="m-prewrap">{profile.profile.referencesText}</p>{state.reviews.map(r=><article className="m-review" key={r.id}><strong>{r.rating}/5</strong><p>{r.body}</p></article>)}</section>}
    {view==='nastaveni'&&<div className="m-card-grid"><section className="p-card m-request-card"><h2>Nastavení účtu</h2><p>{name}<br/>{typeLabels[account.type!]} · {account.name}</p>{canManage(account.role)?<Link className="p-button p-secondary" href="/onboarding/?edit=1&step=1">Upravit údaje a profil</Link>:<p>Profil podnikání upravuje vlastník nebo administrátor.</p>}<Link href="/onboarding/?new=1" className="m-text-button">Přidat jiný typ účtu →</Link></section>{!customer&&<section className="p-card m-request-card"><h2>Vaše obchodní nástroje</h2><p>Databáze firem, uložené seznamy, kampaně a nastavení e-mailového bota.</p><Link className="p-button p-secondary" href="/nastroje/">Otevřít nástroje</Link></section>}{account.type==='COMPANY'&&canManage(account.role)&&<section className="p-card m-request-card"><h2>Členové účtu</h2>{team.map(m=><div key={m.email}><strong>{m.name}</strong><p>{m.email} · {({COMPANY_OWNER:'Vlastník',COMPANY_ADMIN:'Administrátor',COMPANY_MEMBER:'Člen týmu'} as Record<string,string>)[m.role]??m.role}</p></div>)}<p>Správa pozvánek členů týmu bude doplněna v další verzi.</p></section>}</div>}
    <OfferDialog request={offerRequest} onClose={()=>setOfferRequest(null)} onSend={act} errorMessage={error}/>
  </main></div></div>;
}
