'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,FileText,Search,SlidersHorizontal,X} from 'lucide-react';
import {CZECH_REGIONS,regionLabel} from '@/lib/company-types';
import type {Service} from '@/lib/accounts/model';
import {cooperationLabels,requesterLabels,type Offer,type MarketRequest,type RequestFeed} from '@/lib/marketplace/model';
const czk=(value:number)=>new Intl.NumberFormat('cs-CZ',{style:'currency',currency:'CZK',maximumFractionDigits:0}).format(value);
export function RequestBrowser({services,offers,busy,onOffer}:{services:Service[];offers:Offer[];busy:boolean;onOffer:(request:MarketRequest)=>void}){
  const [scope,setScope]=useState('all'),[search,setSearch]=useState(''),[service,setService]=useState(''),[region,setRegion]=useState(''),[page,setPage]=useState(1);
  const [requesterType,setRequesterType]=useState(''),[cooperationType,setCooperationType]=useState('');
  const [feed,setFeed]=useState<RequestFeed>({items:[],total:0,page:1,pages:1}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [expanded,setExpanded]=useState<string[]>([]);
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setError('');
    const timer=setTimeout(()=>{void fetch('/api/marketplace/?'+new URLSearchParams({scope,q:search,service,region,requesterType,cooperationType,page:String(page)}),{signal:controller.signal,cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Poptávky se nepodařilo načíst.');return data;}).then(data=>setFeed(data)).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);
    return()=>{controller.abort();clearTimeout(timer);};
  },[scope,search,service,region,requesterType,cooperationType,page,retry]);
  function reset(){setRequesterType('');setCooperationType('');setSearch('');setService('');setRegion('');setScope('all');setPage(1);}
  return <section className="m-request-browser" aria-label="Procházet poptávky">
    <div className="m-request-tabs" aria-label="Výběr poptávek">{[['all','Všechny poptávky'],['recommended','Doporučené pro vás']].map(([id,label])=><button key={id} aria-pressed={scope===id} className={scope===id?'active':''} onClick={()=>{setScope(id);setPage(1);}}>{id==='all'?<Search size={17}/>:<SlidersHorizontal size={17}/>} {label}</button>)}</div>
    <p className="m-help">{scope==='all'?'Prohlédněte si otevřené poptávky ze všech oborů a celé republiky. U zajímavé poptávky můžete rovnou poslat nabídku.':'Poptávky podle služeb a oblasti z vašeho profilu. Pro hledání mimo profil přepněte na Všechny poptávky.'}</p>
    <div className="m-filters"><label><span>Co hledáte?</span><input aria-label="Hledat poptávku" placeholder="Název, popis nebo město" value={search} maxLength={160} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label><span>Obor</span><select aria-label="Obor" value={service} onChange={e=>{setService(e.target.value);setPage(1);}}><option value="">Všechny obory</option>{services.filter(s=>!s.parentId).map(root=><optgroup label={root.name} key={root.id}>{[root,...services.filter(s=>s.parentId===root.id)].map(s=><option value={s.id} key={s.id}>{s.parentId?'↳ ':''}{s.name}</option>)}</optgroup>)}</select></label><label><span>Kraj</span><select aria-label="Kraj" value={region} onChange={e=>{setRegion(e.target.value);setPage(1);}}><option value="">Celá republika</option>{CZECH_REGIONS.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><label><span>Zadavatel</span><select aria-label="Zadavatel" value={requesterType} onChange={e=>{setRequesterType(e.target.value);setPage(1);}}><option value="">Všichni zadavatelé</option>{Object.entries(requesterLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Typ spolupráce</span><select aria-label="Typ spolupráce" value={cooperationType} onChange={e=>{setCooperationType(e.target.value);setPage(1);}}><option value="">Všechny spolupráce</option>{Object.entries(cooperationLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
    <div className="m-feed-summary"><p role="status">{loading?'Načítání poptávek…':error?'':`Nalezeno poptávek: ${feed.total}`}</p>{(search||service||region||requesterType||cooperationType||scope!=='all')&&<button className="m-text-button" onClick={reset}><X size={15}/> Zrušit filtry</button>}</div>
    {error?<div className="p-error" role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>Zkusit znovu</button></div>:!loading&&feed.items.length===0?<div className="p-card m-feed-empty"><FileText size={32}/><h2>Tomuto výběru zatím nic neodpovídá.</h2><p>Zkuste širší obor, jiný kraj nebo si prohlédněte všechny otevřené poptávky.</p><button className="p-button p-secondary" onClick={reset}>Zobrazit všechny poptávky</button></div>:<div className="m-card-grid" aria-busy={loading}>{!loading&&feed.items.map(r=>{const sent=offers.some(o=>o.requestId===r.id);return <article className="p-card m-request-card" key={r.id}><div className="m-card-meta"><span className="p-badge">{services.find(s=>s.id===r.serviceId)?.name}</span><small>{new Date(r.createdAt).toLocaleDateString('cs-CZ')}</small></div><h3>{r.title}</h3><div className="m-request-labels"><span className="p-badge">{requesterLabels[r.requesterType]}</span><span className="p-badge">{cooperationLabels[r.cooperationType]}</span></div><p>{r.city} · {regionLabel(r.region)}</p><p className={expanded.includes(r.id)?'m-prewrap':'m-clamp'}>{r.description}</p>{r.description.length>160&&<button className="m-text-button" aria-expanded={expanded.includes(r.id)} onClick={()=>setExpanded(ids=>ids.includes(r.id)?ids.filter(id=>id!==r.id):[...ids,r.id])}>{expanded.includes(r.id)?'Skrýt podrobnosti':'Celý popis poptávky'}</button>}<div className="m-card-meta"><strong>{r.budgetCzk===null?'Rozpočet dohodou':czk(r.budgetCzk)}</strong>{sent&&<span className="p-badge">Nabídka odeslána</span>}</div><div className="m-form-actions"><button className="p-button" disabled={busy} onClick={()=>onOffer(r)}>{sent?'Poslat další nabídku zdarma':'Poslat nabídku zdarma'} <ArrowRight size={16}/></button><p className="m-help">Chat až po přijetí nabídky · odemknutí za 49 kreditů</p></div></article>;})}</div>}
    {!loading&&!error&&feed.pages>1&&<nav className="m-feed-pagination" aria-label="Stránkování poptávek"><button className="p-button p-secondary" disabled={feed.page<=1} onClick={()=>setPage(feed.page-1)}><ArrowLeft size={16}/> Předchozí</button><span>{feed.page} / {feed.pages}</span><button className="p-button p-secondary" disabled={feed.page>=feed.pages} onClick={()=>setPage(feed.page+1)}>Další <ArrowRight size={16}/></button></nav>}
  </section>;
}
