import {HomeLink} from '@/components/prospekto/home-link';
import {redirect} from 'next/navigation';
import {getChatGPTUser,chatGPTSignInPath,chatGPTSignOutPath} from '@/app/chatgpt-auth';
import {getProfile} from '@/lib/panel/store';
import {Logo} from '@/components/prospekto/logo';
import {Registration} from './registration';
import {Check,Database,Mail,SlidersHorizontal,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import '@/app/panel/panel.css';
export async function AuthPage({login=false}:{login?:boolean}){const user=await getChatGPTUser();let exists=false,error=false;if(user){try{exists=!!await getProfile(user);}catch{error=true;}}if(exists)redirect('/panel/');return <main className="p-auth"><section className="p-auth-story"><Logo plain/><div><h1>Vaše další<br/>příležitost začíná tady.</h1><p>Firmy, kontakty a vaše obchodní aktivity.<br/>V jednom přehledném prostoru.</p><ul>{[[Database,'Kontakty, které snadno najdete'],[Mail,'Kampaně s osobním přístupem'],[SlidersHorizontal,'Váš e-mail bot pod kontrolou']].map(([Icon,title])=>{const I=Icon as typeof Database;return <li key={title as string}><I size={21}/>{title as string}</li>;})}</ul></div><span className="p-auth-bottom">Méně hledání. Více příležitostí.</span></section><section className="p-auth-content"><HomeLink className="p-back"/><div className="p-auth-card"><span className="p-round-icon"><ShieldCheck size={25}/></span><h2>{user?'Ještě kousek a jste uvnitř.':login?'Vítejte zpět.':'Vytvořte si účet.'}</h2><p>{user?'Dokončete registraci a otevřete svůj pracovní prostor.':login?'Přihlaste se a pokračujte ve svém pracovním prostoru.':'Začněte s Prospektem a mějte svůj obchod na jednom místě.'}</p>{error?<div className="p-notice">Registrace není momentálně dostupná. <a href="/registrace/">Zkusit znovu</a></div>:user?<Registration name={user.fullName??''} email={user.email}/>:<><Button asChild className="p-button p-signin"><a href={chatGPTSignInPath('/registrace/')} target="_top">{login?'Přihlásit se přes ChatGPT':'Pokračovat přes ChatGPT'}</a></Button><p className="p-muted">Přihlášení zabezpečuje ChatGPT. Při prvním vstupu si dokončíte registraci do Prospekta.</p><div className="p-auth-points"><span><Check size={16}/> Vlastní pracovní prostor</span><span><Check size={16}/> Uložené seznamy a koncepty</span></div></>}{user?<a className="p-text-link" href={chatGPTSignOutPath('/registrace/')} target="_top">Použít jiný účet</a>:<p className="p-auth-switch">{login?'Ještě nemáte účet?':'Už máte účet?'} <a href={login?'/registrace/':'/prihlaseni/'}>{login?'Zaregistrovat se':'Přihlásit se'}</a></p>}</div><p className="p-auth-foot">© {new Date().getFullYear()} Prospekto</p></section></main>;}
