'use client';
import {LogoutButton} from './logout-button';
import Link from 'next/link';
import Image from 'next/image';
import {useCallback,useEffect,useState} from 'react';
import {Database,List,Mail,BarChart3,Ban,SlidersHorizontal,LogOut,Settings,Trash2,FolderOpen,Check,Info,X,CheckCircle2,PauseCircle,ShieldCheck} from 'lucide-react';
import {HomeLink} from '@/components/prospekto/home-link';
import {Logo} from '@/components/prospekto/logo';
import {WorkspaceTabs} from '@/components/prospekto/workspace-tabs';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Contacts,type SaveAction} from './contacts';
import {Campaigns} from './campaigns';
import {BotSettingsPanel} from './bot-settings';
import {PanelButton,Field,Empty,Notice} from './ui';
import {panelRequest,dateLabel,downloadText} from '@/lib/panel/client';
import type {PanelState,SavedList,Suppression} from '@/lib/panel/model';
import type {Company,CompanyPage} from '@/lib/company-types';
const nav=[['contacts','Databáze firem',Database],['lists','Moje seznamy',List],['campaigns','Kampaně',Mail],['results','Výsledky',BarChart3],['blocks','Blokace',Ban],['bot','E-mail bot',SlidersHorizontal]] as const;
type View=typeof nav[number][0]|'account';
export function Panel({initial,initialDatabase}:{initial:PanelState;initialDatabase:CompanyPage<Company>}){
 const[companies,setCompanies]=useState(initialDatabase.items);
 const rememberCompanies=useCallback((items:Company[])=>{setCompanies(previous=>[...new Map([...previous,...items].map(company=>[company.id,company])).values()]);},[]);
 const[state,setState]=useState(initial),[view,setView]=useState<View>('contacts'),[busy,setBusy]=useState(false),[toast,setToast]=useState<{text:string;error:boolean}|null>(null),[selected,setSelected]=useState<string[]>([]),[activeList,setActiveList]=useState<SavedList|null>(null),[campaignSeed,setCampaignSeed]=useState<string[]|null>(null),[campaignKey,setCampaignKey]=useState(0);
 useEffect(()=>{function loadView(){const value=new URLSearchParams(window.location.search).get('view');if(value==='account'||nav.some(v=>v[0]===value))setView(value as View);else setView('contacts');}loadView();window.addEventListener('popstate',loadView);return()=>window.removeEventListener('popstate',loadView);},[]);
 useEffect(()=>{if(!toast||toast.error)return;const timer=setTimeout(()=>setToast(null),6000);return()=>clearTimeout(timer);},[toast]);
 function navigate(next:View){setView(next);window.history.pushState(null,'',next==='contacts'?'/nastroje/':`/nastroje/?view=${next}`);window.scrollTo({top:0,behavior:'instant'});if(next==='campaigns'){setCampaignSeed(null);setCampaignKey(v=>v+1);}}
 const save:SaveAction=async(action,message)=>{if(busy)return null;setBusy(true);setToast(null);try{const result=await panelRequest(action);setState(result);setToast({text:message,error:false});return result;}catch(e){setToast({text:(e as Error).message,error:true});return null;}finally{setBusy(false);}};
 function createCampaign(){setCampaignSeed([...selected]);setCampaignKey(v=>v+1);setView('campaigns');window.history.pushState(null,'','/nastroje/?view=campaigns');window.scrollTo({top:0,behavior:'instant'});}
 return <div className="p-app"><a className="skip-link" href="#panel-content">Přejít na obsah</a><aside className="p-sidebar"><div className="p-sidebar-brand"><Logo plain/><WorkspaceTabs active="companies"/></div><nav aria-label="Pracovní prostor">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>navigate(id)} className={view===id?'active':''} aria-current={view===id?'page':undefined}><Icon size={19}/><span>{label}</span>{id==='lists'&&state.lists.length>0&&<small>{state.lists.length}</small>}</button>)}</nav><div className="p-workspace-card"><span>Váš pracovní prostor</span><strong>{state.profile.workspace}</strong><small>Nástroje dodavatele</small></div><button className={`p-sidebar-account ${view==='account'?'active':''}`} onClick={()=>navigate('account')}><Settings size={19}/> Účet a nastavení</button><LogoutButton className="p-sidebar-exit"><LogOut size={17}/> Odhlásit se</LogoutButton></aside><div className="p-main"><header className="p-topbar"><span className="p-workspace-crumb">Pracovní prostor <span>/</span> <strong>{state.profile.workspace}</strong></span><Link className="p-mobile-brand" href="/"><Image src="/brand/prospekto-wordmark.svg?v=20260930-original" alt="Prospekto" width={140} height={32}/></Link><div><span className="p-badge">{initialDatabase.ready?'Databáze firem':'Ukázková data'}</span><button className="p-user" onClick={()=>navigate('account')} aria-label="Můj účet"><span className="p-avatar">{state.profile.name.split(' ').map(n=>n[0]).slice(0,2).join('').toUpperCase()}</span><strong>{state.profile.name}</strong></button></div></header><main id="panel-content" className="p-content"><HomeLink className="p-return-home"/>
 {view==='contacts'&&<Contacts key={activeList?.id??'all'} initialData={initialDatabase} onLoaded={rememberCompanies} selected={selected} setSelected={setSelected} onCampaign={createCampaign} onSave={save} busy={busy} activeList={activeList} clearList={()=>setActiveList(null)} suppressed={state.suppressions.map(s=>s.email)}/>}
 {view==='lists'&&<Lists state={state} onSave={save} busy={busy} onContacts={()=>{setActiveList(null);navigate('contacts');}} onOpen={list=>{setActiveList(list);setSelected([]);navigate('contacts');}}/>}
 {view==='campaigns'&&<Campaigns key={campaignKey} state={state} companies={companies} onSave={save} busy={busy} seed={campaignSeed} onContacts={()=>navigate('contacts')}/>}
 {view==='bot'&&<BotSettingsPanel initial={state.settings} onSave={save} busy={busy}/>}
 {view==='blocks'&&<Blocks state={state} onSave={save} busy={busy}/>}
 {view==='results'&&<><div className="p-heading"><div><h1>Výsledky pod kontrolou.</h1><p>Skutečný stav každého pokusu o odeslání.</p></div><PanelButton secondary onClick={()=>navigate('bot')}>Nastavení bota</PanelButton></div><div className="p-stats"><article><span className="p-stat-icon"><CheckCircle2 size={20}/></span><strong>0</strong><span>přijato odesílacím serverem</span></article><article><span className="p-stat-icon"><PauseCircle size={20}/></span><strong>0</strong><span>čeká na odeslání</span></article><article><span className="p-stat-icon"><ShieldCheck size={20}/></span><strong>0</strong><span>nejistých výsledků</span></article></div><Empty title="Zatím jste nic neodeslali." action={<PanelButton onClick={()=>navigate('campaigns')}>Připravit kampaň</PanelButton>}>Jakmile bude zapojený e-mail bot, uvidíte tady průběh kampaní a jejich výsledky.</Empty><Notice>„Přijato serverem“ neznamená doručeno do schránky. Nejisté výsledky budou vyžadovat ruční ověření před dalším pokusem.</Notice></>}
 {view==='account'&&<Account state={state}/>}
 </main></div><nav className="p-bottom-nav" aria-label="Mobilní pracovní prostor">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>navigate(id)} aria-current={view===id?'page':undefined}><Icon size={21}/><span>{id==='contacts'?'Kontakty':id==='lists'?'Seznamy':label}</span></button>)}</nav>{toast&&<div className={`p-toast ${toast.error?'p-toast-error':''}`} role={toast.error?'alert':'status'}>{toast.error?<Info size={19}/>:<Check size={19}/>}<span>{toast.text}</span><button onClick={()=>setToast(null)} aria-label="Zavřít oznámení"><X size={17}/></button></div>}</div>;
}
function Lists({state,onSave,busy,onOpen,onContacts}:{state:PanelState;onSave:SaveAction;busy:boolean;onOpen:(list:SavedList)=>void;onContacts:()=>void}){const[remove,setRemove]=useState<SavedList|null>(null);return <><div className="p-heading"><div><h1>Firmy, ke kterým se vracíte.</h1><p>Vlastní výběry kontaktů přehledně na jednom místě.</p></div><PanelButton onClick={onContacts}>Vybrat firmy</PanelButton></div>{state.lists.length?<div className="p-list-grid">{state.lists.map(list=><article className="p-card p-list-card" key={list.id}><div className="p-card-heading"><span className="p-record-icon"><FolderOpen size={24}/></span><button className="p-icon-button" aria-label={`Odstranit seznam ${list.name}`} onClick={()=>setRemove(list)}><Trash2 size={18}/></button></div><h2>{list.name}</h2><p>{list.companyIds.length} firem · {dateLabel(list.updatedAt)}</p><PanelButton secondary onClick={()=>onOpen(list)}>Otevřít seznam</PanelButton></article>)}</div>:<Empty title="Místo pro vaše oblíbené firmy." action={<PanelButton onClick={onContacts}>Prohlédnout databázi</PanelButton>}>Vyberte firmy v databázi a uložte si je do prvního seznamu.</Empty>}<Dialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null);}}><DialogContent className="p-dialog"><DialogTitle>Odstranit seznam?</DialogTitle><DialogDescription>Seznam „{remove?.name}“ zmizí. Firmy v databázi zůstanou.</DialogDescription><PanelButton danger disabled={busy} onClick={async()=>{if(remove&&await onSave({action:'delete-list',id:remove.id},'Seznam byl odstraněn.'))setRemove(null);}}>Odstranit seznam</PanelButton></DialogContent></Dialog></>;}
function Blocks({state,onSave,busy}:{state:PanelState;onSave:SaveAction;busy:boolean}){const[email,setEmail]=useState(''),[reason,setReason]=useState('Žádost o odhlášení'),[remove,setRemove]=useState<Suppression|null>(null);return <><div className="p-heading"><div><h1>Respektujte každé „ne“.</h1><p>Odhlášené a blokované adresy ve vašem pracovním prostoru.</p></div><PanelButton secondary disabled={!state.suppressions.length} onClick={()=>downloadText('prospekto-blokovane-adresy.json',JSON.stringify(state.suppressions.map(({email,reason,createdAt})=>({email,reason,createdAt})),null,2),'application/json')}>Exportovat blokace</PanelButton></div><div className="p-settings-grid"><section className="p-card"><h2>Přidat blokovanou adresu</h2><form className="p-form" onSubmit={async e=>{e.preventDefault();if(await onSave({action:'suppress',data:{email,reason}},'Adresa byla přidána do blokací.'))setEmail('');}}><Field label="E-mailová adresa"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="kontakt@firma.cz" maxLength={254} required/></Field><Field label="Důvod blokace"><input value={reason} onChange={e=>setReason(e.target.value)} minLength={2} maxLength={300} required/></Field><PanelButton disabled={busy} type="submit">Přidat blokaci</PanelButton></form></section><section className="p-card p-sage-card"><ShieldCheck size={28}/><h2>Blokace má přednost.</h2><p>Adresa se označí v kontaktech a při simulaci kampaně. Po připojení bota musí být kontrolována před každým odesláním.</p><p>Žádosti o odhlášení zpracujte ručně z adresy pro odpovědi.</p></section></div><div className="p-table-heading"><h2>Blokované adresy <span className="p-badge">{state.suppressions.length}</span></h2></div>{state.suppressions.length?<div className="p-records">{state.suppressions.map(s=><article className="p-record" key={s.id}><Ban size={23}/><div className="p-record-copy"><h3>{s.email}</h3><p>{s.reason}</p><small>{dateLabel(s.createdAt)}</small></div><button className="p-icon-button" aria-label={`Odebrat blokaci ${s.email}`} onClick={()=>setRemove(s)}><Trash2 size={18}/></button></article>)}</div>:<div className="p-card p-no-results"><Ban size={25}/><h3>Zatím žádné blokované adresy.</h3></div>}<Dialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null);}}><DialogContent className="p-dialog"><DialogTitle>Odebrat blokaci?</DialogTitle><DialogDescription>Adresa {remove?.email} přestane být blokovaná. Odhlášení odebírejte jen na základě nového doloženého oprávnění.</DialogDescription><PanelButton danger disabled={busy} onClick={async()=>{if(remove&&await onSave({action:'unsuppress',id:remove.id},'Blokace byla odebrána.'))setRemove(null);}}>Odebrat blokaci</PanelButton></DialogContent></Dialog></>;}
function Account({state}:{state:PanelState}){return <><div className="p-heading"><div><h1>Nastavení účtu.</h1><p>Spravujte své údaje a profil podnikání na jednom místě.</p></div></div><div className="p-settings-grid"><section className="p-card p-form"><h2>Účet a nastavení</h2><p>{state.profile.name}<br/>{state.profile.workspace}</p><p>E-mail účtu: {state.profile.email}</p><Link className="p-button p-secondary" href="/onboarding/?edit=1&step=1">Upravit údaje a profil</Link><Link href="/onboarding/?new=1" className="p-text-link">Přidat jiný typ účtu →</Link></section><aside className="p-support-stack"><section className="p-card p-dark-card"><h2>Prospekto je vaše místo.</h2><p>Registrováno {dateLabel(state.profile.createdAt)}</p><ul className="p-checklist"><li><Check size={17}/> {state.lists.length} uložených seznamů</li><li><Check size={17}/> {state.campaigns.length} konceptů kampaní</li><li><Check size={17}/> Soukromé nastavení bota</li></ul></section><section className="p-card p-form"><h2>Přihlášení k účtu</h2><p>Po odhlášení zůstávají vaše data uložená a panel se uzamkne.</p><LogoutButton className="p-button p-secondary"/><Link className="p-text-link" href="/">Zpět na veřejný web</Link></section></aside></div></>;}
