import { sqliteTable, text, integer, index, uniqueIndex, primaryKey } from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull(),workspace:text('workspace').notNull(),createdAt:text('created_at').notNull()});
export const lists=sqliteTable('saved_lists',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>profiles.id),name:text('name').notNull(),companyIds:text('company_ids').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('lists_owner').on(t.ownerId)]);
export const campaigns=sqliteTable('campaigns',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>profiles.id),name:text('name').notNull(),purpose:text('purpose').notNull(),subject:text('subject').notNull(),body:text('body').notNull(),companyIds:text('company_ids').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('campaigns_owner').on(t.ownerId)]);
export const botSettings=sqliteTable('bot_settings',{ownerId:text('owner_id').primaryKey().references(()=>profiles.id),settings:text('settings').notNull(),updatedAt:text('updated_at').notNull()});
export const suppressions=sqliteTable('suppressions',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>profiles.id),email:text('email').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('suppressions_owner_email').on(t.ownerId,t.email)]);

export const catalogCompanies=sqliteTable('catalog_companies',{
 id:text('id').primaryKey(),name:text('name').notNull(),sortName:text('sort_name').notNull(),ico:text('ico').notNull(),phones:text('phones').notNull(),emails:text('emails').notNull(),websites:text('websites').notNull(),categories:text('categories').notNull(),city:text('city').notNull().default(''),region:text('region').notNull().default(''),sourceUrl:text('source_url').notNull(),fetchedAt:text('fetched_at').notNull(),
},t=>[index('catalog_name').on(t.sortName,t.id),index('catalog_region').on(t.region,t.sortName),index('catalog_ico').on(t.ico)]);
export const catalogCategories=sqliteTable('catalog_categories',{companyId:text('company_id').notNull().references(()=>catalogCompanies.id),category:text('category').notNull()},t=>[primaryKey({columns:[t.category,t.companyId]})]);
export const catalogMeta=sqliteTable('catalog_meta',{id:text('id').primaryKey(),ready:integer('ready').notNull().default(0),total:integer('total').notNull().default(0),withEmail:integer('with_email').notNull().default(0),regionsAvailable:integer('regions_available').notNull().default(0),importedAt:text('imported_at').notNull().default('')});
export const catalogChunks=sqliteTable('catalog_chunks',{id:integer('id').primaryKey(),hash:text('hash').notNull(),rows:integer('rows').notNull()});
